### ISSUE TITLE
feat: support custom window title

### ISSUE THREAD

**Issue by AndersDJohnson** [coston/react-window-ui#20]
Could add a prop to pass a custom title to the window, e.g., `Untitled` here:

<img width="508" alt="Screen Shot 2020-04-08 at 6 38 48 PM" src="https://user-images.githubusercontent.com/615381/78843371-3b16ee00-79c8-11ea-9b1e-4b47b38d3321.png">

**Comment by coston** [comment]
@AndersDJohnson thank you submitting this issue. I think it’s a great idea. Would you like to submit a PR for this feature?
